language: rust
cache: cargo
os: 
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
branches:
  only:
    - master
matrix:
  allow_failures:
  - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
