[package]
name = "cluFlock"
version = "0.2.2"
authors = ["Denis Kotlyarov (Денис Котляров) <denis2005991@gmail.com>"]
repository = "https://github.com/clucompany/cluFlock.git"
license = " Apache-2.0"
readme = "README.md"
edition = "2018"

keywords = ["flock", "unix_flock", "flock_lock_methods", "clucompany"]
categories = ["development-tools"]

description = "Establishes and safely deletes advisory blocking on the open file."

[dependencies]
libc = "0.2.51"
