[package]
name = "cluFlock"
version = "1.2.3"
authors = ["Denis Kotlyarov (Денис Котляров) <denis2005991@gmail.com>"]
repository = "https://github.com/clucompany/cluFlock.git"
license = " Apache-2.0"
readme = "README.md"
edition = "2018"

keywords = ["flock", "unix_flock", "flock_lock_methods", "clucompany"]
categories = ["development-tools::ffi"]

description = "Establishes and safely deletes advisory blocking on the open file."

[features]
default = []
nightly = ["cluFullTransmute"]

[dependencies]
libc = "0.2.62"
cluFullTransmute = {version = "1.0.1", optional = true }

#[target.'cfg(nightly)'.dependencies]
#cluFullTransmute = "1.0.1"
